name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 使用 micromamba 创建 conda 环境（从 environment.yml）
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          micromamba-version: "1.5.8"
          python-version: |
            3.10
            3.11

      - name: Show env
        shell: bash -l {0}
        run: |
          micromamba info
          python -V
          python -c "import sys; print(sys.executable)"
          pip list

      - name: Lint & Type
        shell: bash -l {0}
        run: |
          black --check .
          flake8 .
          mypy turtletrader

      - name: Tests
        shell: bash -l {0}
        run: |
          pytest -q
